# Generated by Django 2.0.6 on 2018-11-12 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cnisblog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user',
        ),
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
